services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  trader:
    image: ghcr.io/hnizamoglu/binance-trader:latest
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  orchestrator:
    image: ghcr.io/hnizamoglu/binance-trader:latest
    environment:
      - 'SPRING_PROFILES_ACTIVE=orchestrator'
    depends_on:
      - rabbitmq
    links:
      - rabbitmq