name: Build & Upload
run-name: Build & Upload
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-central-1'
  AWS_DEFAULT_OUTPUT: json
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build
        run: |
          ./gradlew build -x test
      - name: Upload JAR to S3
        run: |
          cp build/libs/binance-api-test-0.0.1-SNAPSHOT.jar build/libs/app.jar
#          aws s3 cp build/libs/app.jar s3://trader-artifact-bucket
      - name: Login to Github CR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCRIO_TOKEN}}
      - name: Build & Push Image
        run: |
          docker build . --tag ghcr.io/hnizamoglu/binance-trader:latest
          docker push ghcr.io/hnizamoglu/binance-trader:latest
