name: AWS Deploy Flow
run-name: Not sure what this is
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Starting"
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=trader" | jq '.Reservations[0].ReservationId')
          echo $INSTANCE_ID