name: AWS Deploy Flow
run-name: Deploy to AWS
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-central-1'
      AWS_DEFAULT_OUTPUT: json
    steps:
      - name: list aws instances
        run: | 
          echo "Starting"
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=trader" | jq '.Reservations[0].ReservationId')
          echo $INSTANCE_ID
