name: Build & Upload
run-name: Build & Upload
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-central-1'
  AWS_DEFAULT_OUTPUT: json
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build
        run: |
          ./gradlew build -x test
      - name: Upload JAR to S3
        run: |
          cp build/libs/binance-api-test-0.0.1-SNAPSHOT.jar build/libs/app.jar
          aws s3 cp build/libs/app.jar s3://trader-artifact-bucket
  restart-app:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: ${{ startsWith(github.event.head_commit.message, 'deploy:') && needs.deploy.outputs.deploy-status == 'true'}}
    steps:
      - name: Send Restart Command
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:type,Values=trader" \
            --parameters 'commands=["AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' aws s3 cp s3://trader-artifact-bucket/restart-trader.sh /home/ec2-user/restart-trader.sh", "chmod 755 /home/ec2-user/restart-trader.sh", "AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' sh /home/ec2-user/restart-trader.sh"]'
      - name: Send Restart for Orchestrator
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:type,Values=orchestrator" \
            --parameters 'commands=["AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' aws s3 cp s3://trader-artifact-bucket/restart-orchestrator.sh /home/ec2-user/restart-orchestrator.sh", "chmod 755 /home/ec2-user/restart-orchestrator.sh", "AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' sh /home/ec2-user/restart-orchestrator.sh"]'
