name: Restart App
run-name: Restart App
on:
  push:
    paths:
      - '**deploy-tag.txt'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-central-1'
  AWS_DEFAULT_OUTPUT: json
jobs:
  restart-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send Restart Command
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:type,Values=trader" \
            --parameters 'commands=["aws s3 cp s3://trader-artifact-bucket/restart-trader.sh /home/ec2-user/restart-trader.sh", "chmod 755 /home/ec2-user/restart-trader.sh", "sh /home/ec2-user/restart-trader.sh"]'
      - name: Send Restart for Orchestrator
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:type,Values=orchestrator" \
            --parameters 'commands=["aws s3 cp s3://trader-artifact-bucket/restart-orchestrator.sh /home/ec2-user/restart-orchestrator.sh", "chmod 755 /home/ec2-user/restart-orchestrator.sh", "sh /home/ec2-user/restart-orchestrator.sh"]'